# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=7, default=None, max_digits=7, null=True, verbose_name='Цена')),
                ('edition_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Antiques',
            fields=[
                ('goodsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.GoodsBase')),
            ],
            options={
                'verbose_name': 'Антиквариат',
                'verbose_name_plural': 'Антиквариат',
            },
            bases=('goods.goodsbase',),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.GoodsBase')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Другие товары',
            },
            bases=('goods.goodsbase',),
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('goodsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.GoodsBase')),
                ('creation_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата создания')),
                ('size', models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='Размер')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Authors', verbose_name='Автор')),
                ('genre', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Genres', verbose_name='Стили')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картины',
            },
            bases=('goods.goodsbase',),
        ),
        migrations.AddField(
            model_name='images',
            name='good',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsBase'),
        ),
        migrations.AddField(
            model_name='goodsbase',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='categories.Categories', verbose_name='Категории'),
        ),
    ]
