# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='goodsbase',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена'),
        ),
    ]
