# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('goods', '0002_auto_20171012_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='genre',
        ),
        migrations.AddField(
            model_name='goodsbase',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Authors', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='goodsbase',
            name='creation_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='goodsbase',
            name='genre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Genres', verbose_name='Жанр'),
        ),
    ]
