# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20171224_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsbase',
            name='creation_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Период создания'),
        ),
        migrations.AlterField(
            model_name='goodsbase',
            name='edition_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления'),
        ),
    ]
