# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20171224_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsbase',
            name='category',
        ),
    ]
