# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_goodsbase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsbase',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Автор'),
        ),
    ]
