# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20171224_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
